spring.application.name=security
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
api.security.token.secret =${JWT_SECRET}
# 2. Configurações do Hibernate (A Mágica do JPA)
# 'update' diz para o Spring: "Leia minhas entidades e crie as tabelas sozinho se elas não existirem!"
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
server.error.include-message=always
server.error.include-stacktrace=never
# Email (Mailtrap pra dev)
spring.mail.host=${MAIL_HOST:sandbox.smtp.mailtrap.io}
spring.mail.port=${MAIL_PORT:2525}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Email ? config de aplicação
app.email.from=nao-responda@revele.com.br
app.email.from-nome=Revele Cosméticos

app.cors.allowed-origins=http://localhost:5173
# Habilita Swagger UI (desabilitado por default na 3.x)
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

# Caminhos
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Ordenação
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha